- index.html
- style.css
#4  Fixed the issue with adding appropriate CSS file to be used in the project
#5 Theres now a a registration button for the user to later interact with
> User welcome and Registration boxes task 

- index.html
- style.css
- Added mainbar and centered it with the window
- Opaque background colors are temporarily used for styling
- Temporarily added filler text for formatting
> Centered mainbar in window

- mongo_registration_database/registration_add_documents.js
- mongo_registration_database/registration_collection_creation.js
- mongo_registration_database/registration_query.js
https://github.com/Software-Process/Software-Process.github.io/issues/27
Creating a collection for registration data, creating mock data and mock query
> Prototype Registration database and mock query

- DataManager.js
Issue #33  : Created a collection called "posts" in DataManager.js which will be used to keep track of data regarding posts
> Implemented a collection in MongoDB database for data regarding posts

- DataManager.js
Added mock data into the "posts" collection of the database to simulate questions on the website and to verify that the database is in fact keeping the data
> Adding mock data to the database to simulate questions on the website

- README.md
#31 Included the following sections: Objective, Description, Team members and Technologies
> Updating the ReadMe file with a more accurate description of the project

- footer.html
- header.html
- index.html
- style.css
#26: I added two files for the header and footer to be included on all the pages. CSS and text is temporary and will change in the future. NOTE: In order for the include-html to work, the website needs to be hosted (locally is good). Will put instructions on how to use the "w3-inlcude-html" on issue page.
> Completed Issue #26: Common Header and Footer

- question-prompt.html
Added question prompt page with header/footer, removed unnecessary wood background from repository. Completes issue #24.
> Added simple question prompt page, cleaned up repo.

- index.html
- style.css
#20: The banner includes the website name (to be determined eventually), as well as a vertical list of sample questions. You can see the question titles as well as their score. Finally, there is a "Ask a Question" button at the bottom of the page.
> Created homepage with a banner, list of questions, and basic styling.

- README.md
The spelling for my name was fixed in the Team Member section.
> Fixed typo in team member Panorea's name

- Website.iml
- app.js
- bin/www
- models/question.js
- package-lock.json
- package.json
- public/stylesheets/style.css
- routes/index.js
- routes/questions.js
- routes/users.js
- views/error.hbs
- views/index.hbs
- views/layout.hbs
Added Express backend framework, sample queries and database connection, [#44]
> Added Express framework. [#44]

- travis.yml
Added the travis.yml file specifying the language. [#49]
> Adding Travis CI [#49]

- .travis.yml
- travis.yml
> Renamed Travis file [#49]

- .travis.yml
- package.json
Created placeholder test and updated node.js version. [#49]
> Updated Travis functionality. [#49]

- .gitignore
> [#66] Added .gitignore file, preventing libraries from being added

- question.css
- question.html
- questionFrontEnd.js
Doing a pull request for issue #45 I want to receive some feedback from other members of the team. NOTE: The issue is not finished! Only front end is done, still have to implement some back end features.
> Issue #45: Front end features implemented

- routes/question-prompt.js
- views/index.hbs
- views/partials/header.hbs
Ensured that the questions on the index page link to the individual question page when clicked. [#44] [#55]
> Added the link between the index page and the individual page [#44] [#55]

- AboutUs.html
This About Us page has been done. It has FAQ that has the basic ideas of our page as well as a contact area so that we can put our contact info in it.
> "About Us" Page [#63].

- app.js
- models/question.js
- package-lock.json
- package.json
- public/javascripts/questionFrontEnd.js
- public/stylesheets/question.css
- routes/question-prompt.js
- routes/question.js
- routes/questions.js
- views/question.hbs
Reply system, modified schema to include a nested array. [#58]
Voting system with persistent scores. [#61]
> Persistent voting scores and replies. [#58, #61]

- .travis.yml
Updating the Travis file to be able to build and run the unit tests from Jasmine
> Updating Travis CLI to integrate with Karma and Jasmine Testing framework

- karma.conf.js
- package.json
- test/testingSpec.js
Adding dependencies and karma.conf to be able to implement unit test in the project
> Setting up Jasmine and Karma to integrate unit testing [#90]

- .travis.yml
Updated hyphens to dashes. [#90]
> Updated travis.yml [#90]

- app.js
- models/user.js
- package-lock.json
- package.json
- routes/editUserPage.js
- routes/index.js
- routes/loginRegister.js
- routes/question-prompt.js
- routes/userPage.js
- views/edituserpage.hbs
- views/index.hbs
- views/partials/header.hbs
- views/signIn.hbs
- views/userpage.hbs
Users can register, (user name and password only). [#95, #96 ]
Users can log into the website using previously-registered credentials. [#93]
Users can see their user name displayed on the main page and in the profile. [#94]
Users can modify an entry in their profile (bio only) [#97]
> User login system. [#93, #94, #95, #96, #97]

- app.js
- models/question.js
- package-lock.json
- package.json
- routes/aboutUs.js
- routes/index.js
- routes/loginRegister.js
- routes/question.js
- views/aboutus.hbs
- views/edituserpage.hbs
- views/index.hbs
- views/partials/header.hbs
- views/question.hbs
- views/signIn.hbs
Fixed login status not displayed. [#144]
Question voting now implements a nested document query. [#45]
Rudimentary validator for the register page. [#145]
Rudimentary validator for the register page (login function). [#145]
> Login validation, voting and other bug fixes. [#45. #144. #145]

- routes/index.js
- routes/jobPage.js
- routes/userPage.js
[Bug #157]
Fix involved reversing the array of elements (either questions, replies or job postings) retrieved from the database before sending it to the corresponding frontend page.
> Questions, replies and job postings are sorted by most recent [#157]

- app.js
- public/stylesheets/userrankpagestlye.css
- routes/userRankPage.js
- views/partials/header.hbs
- views/userRankPage.hbs
[Task #135]
Implemented the frontend of the user ranking page which will allow recruiters to view all users using tags. Once backend is complete, recruiters will be able provide a list of users based on the score they received from a particular tag.
> Frontend implementation of user ranking page [#135]

- test/editUserPageSpec.js
- test/indexSpec.js
- test/jobPostingPageSpec.js
- test/loginRegisterSpec.js
- test/questionPromptSpec.js
- test/questionSpec.js
- test/userPageSpec.js
Added unit tests to test the different Javascript files in the routes. Successfully create a user, add a user to the database, update a user, retrieve a user. Ensure being able to create a question, add some replies, down vote, up votes, update and retrieve question
> Adding unit tests for testing the different pages [#129]

- app.js
- models/history.js
- models/question.js
- package-lock.json
- package.json
- public/stylesheets/question.css
- routes/question-prompt.js
- routes/question.js
- views/question.hbs
The ability to accept/reject answers is now functional. Vineet can now start the task on user scores.
> Task/Bug #45: Finished Accepting/rejecting of answers both frontend/backend

- models/jobs.js
- routes/jobPage.js
- routes/jobPostingPage.js
- views/jobdescription.hbs
- views/jobpage.hbs
- views/jobposting.hbs
**User story [#123]** 
**task [#151]**
From the view job description page,
Once the user click on the job link, they will be directed to page where they will see the job's description along with the real external URL.
This change also required to add a description posting for the job along with adding database variables.
> [#151] [#123] Job description page

- routes/companyAccount.js
- routes/loginRegister.js
- views/companypage.hbs
- views/question-prompt.hbs
- views/signIn.hbs
Company registration now requiring approval by admin from the company creation page. [#152]
> Company registration and approval. [#152]

- views/userpage.hbs
Users are now able to change color in the user profile and have the change reflected on the main user page and on the external user page.
> Color change is now reflected on the user page. [#146]

- test/companyAccountSpec.js
- test/editUserPageSpec.js
- test/indexSpec.js
- test/jobPageSpec.js
- test/jobPostingPageSpec.js
- test/loginRegisterSpec.js
- test/questionSpec.js
- test/userPageSpec.js
Added tags in the user schema and the tag array into the question schema. Modified tests to make them work.
> [#129] Modified the tests to accommodate the new schemas

- routes/loginRegister.js
The bug required a simple fix to the loginRegister.js route page
> [#181] Fixed the validation leading to app crashing

- routes/questionPrompt.js
- views/index.hbs
- views/questionPrompt.hbs
Some confusion cause a small bug where redirects werent working but is now fixed
> [#180] Fixed all of the redirect issue for question prompt

- views/userpage.hbs
[Bug #186]
Replaced placeholder tag scores with actual user tag scores from the database in userpage.hbs
> Replaced placeholder tag scores in userpage.hbs [#186]

- routes/question.js
- test/companyAccountSpec.js
- test/editUserPageSpec.js
- test/indexSpec.js
- test/jobPageSpec.js
- test/jobPostingPageSpec.js
- test/loginRegisterSpec.js
- test/questionPromptSpec.js
- test/questionSpec.js
- test/userPageSpec.js
[#129]
-Data are now retrieved using IDs.
-Added assertions in unit test to ensure the proper behavior of the unit test.
-Added method to drop collections after the specs have finished executing.
-The following files have been modified:
companyAccountSpec, editUserPageSpec, indexSpec, jobPageSpec, jobPostingPageSpec, loginRegisterSpec, questionPromptSpec, questionSpec, userPageSpec
> [#129] Implemented new method of retrieving data from database and added assertions for unit tests. 

- app.js
- routes/question.js
[#129]  Fixed the routing issues caused by improperly exporting the router and function. Modified both routes/question.js and app.js files.
> [#129] Fixed routing issues when starting local host due to exporting function

- package-lock.json
- views/index.hbs
[#137, bug #192] Fixed the C# display bug, by changing the # key to an HTML symbol.
> [#137, bug #192] C# sorting bugfix. 

- .eslintrc.json
- .gitignore
Added linter configuration file to project repository.
> [#179] Added linter configuration file to project repository

- test/companyAccountSpec.js
- test/editUserPageSpec.js
- test/indexSpec.js
- test/jobPostingPageSpec.js
- test/loginRegisterSpec.js
- test/questionSpec.js
- test/userPageSpec.js
Used linter to automatically replace all single quotes with double quotes.
> [#129] Change test code to comply with styling guidelines
